version: "3.9"

services:
  app:
    build:
      context: .
    container_name: fuzz
    depends_on:
      fuzz-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:root@fuzz-db:5432/fuzz
    ports:
      - "8000:8000"
    networks:
      - fuzz

  fuzz-db:
    image: "postgres:14.2-alpine"
    container_name: fuzz-db
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: fuzz
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username=postgres",
          "--host=127.0.0.1",
          "--port=5432",
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - fuzz

volumes:
  db_volume:

networks:
  fuzz:
    # driver: host
    driver: bridge
